add PR for DUNS memset to initialize flags
daos-stack/hdf5-vol-daos pull request #19
Opened 2021-06-22 21:14 UTC by mchaarawi

Signed-off-by: Mohamad Chaarawi <mohamad.chaarawi@intel.com>

2021-06-22 21:37 UTC, mjean308 approved these changes

2021-06-23 02:44 UTC, brianjmurrell requested changes
Nice!

Just don't forget to update the `Release:` from 2 to 3.

2021-06-23 12:47 UTC, mchaarawi commented
> Nice!
> 
> Just don't forget to update the `Release:` from 2 to 3.

fixed

2021-06-23 12:52 UTC, mjean308 approved these changes

2021-06-23 14:36 UTC, brianjmurrell approved these changes

2021-06-23 14:41 UTC, merged