DAOS-6588 restore Requires for openmpi3-tests package
daos-stack/hdf5-vol-daos pull request #9
Opened 2021-01-22 20:34 UTC by kccain

Signed-off-by: Kenneth Cain <kenneth.c.cain@intel.com>

2021-01-22 21:52 UTC, brianjmurrell requested changes

2021-01-22 21:52 UTC, brianjmurrell commented on hdf5-vol-daos.spec
> +Requires: %{name}-mpich2
```suggestion
Requires: %{name}-mpich2%{?_isa} = %{version}-%{release}
```
is the correct syntax.

2021-01-22 21:52 UTC, brianjmurrell commented on hdf5-vol-daos.spec
> +Requires: %{name}-mpich2
Ditto.

2021-01-22 21:52 UTC, brianjmurrell commented on hdf5-vol-daos.spec
> +Requires: %{name}-openmpi3
Ditto.

2021-01-22 21:52 UTC, brianjmurrell commented on hdf5-vol-daos.spec
> +Requires: %{name}-openmpi3
Ditto.

2021-01-25 20:03 UTC, brianjmurrell approved these changes

2021-01-25 21:18 UTC, brianjmurrell commented
> ￼ kccain requested a review from daos-stack/release-engineering 26 minutes ago

@kccain Testing with this PR on daos@master proved it resolved the issue there?

2021-01-25 21:34 UTC, kccain commented
> > ￼ kccain requested a review from daos-stack/release-engineering 26 minutes ago
> 
> @kccain Testing with this PR on daos@master proved it resolved the issue there?

Yes for the io/daos_vol.py problem (openmpi related test cases) reported in DAOS-6588 a PR based on daos master was created and run with the packages generated by this PR. All cases either were skipped or passed.
https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-4387/2/testReport/(root)/DaosVol/

a successful test run set of logs has also been attached to DAOS-6588
https://jira.hpdd.intel.com/secure/attachment/33978/33978_job-2021-01-23T07.50-ed372d6-io-daos_vol.zip

2021-01-25 21:42 UTC, merged